spring:
  application:
    name: buddy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local

# local 환경
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/buddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret-key: ${SECRET_KEY}
  refresh-key: ${REFRESH_KEY}
