spring:
  application:
    name: buddy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

jwt:
  secret-key: ${SECRET_KEY}
  refresh-key: ${REFRESH_KEY}

naver:
  api:
    host: naveropenapi.apigw.ntruss.com
    path5: /map-direction/v1/driving
    path15: /map-direction-15/v1/driving
    naver-api-client-id: ${NAVER_API_CLIENT_ID}
    naver-api-client-secret: ${NAVER_API_CLIENT_SECRET}
    header1: X-NCP-APIGW-API-KEY-ID
    header2: X-NCP-APIGW-API-KEY

# local 환경
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/buddy?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_NAME}
    password: ${DB_PASSWORD}


# dev 환경
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://rds-test.cfsok8siyava.ap-northeast-2.rds.amazonaws.com:3306/rdstest
    username: ${RDS_NAME}
    password: ${RDS_PASSWORD}


